# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='nickname',
            field=models.TextField(default='Dodo', max_length=60),
        ),
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.TextField(default='Meia', max_length=20),
        ),
        migrations.AddField(
            model_name='players',
            name='words',
            field=models.TextField(default='Eu sou o Dougras', max_length=500, verbose_name='Lema'),
        ),
    ]
